### ISSUE TITLE
Minor edit to work in Python 3

### ISSUE THREAD

**Issue by josiechoi** [robincamille/ezproxy-analysis#2]
Thank you for sharing your code. It works beautifully for me!
Also, just to let you know that some minor edit would require for your code to work in Python 3 environment. 
Pretty easy fix. Just the syntax for print needs to be changed (now in bracket) 
Thanks again!

Josephine

**Comment by robincamille** [comment]
Thank you Josephine! I'll work on making this more up-to-date...

**Comment by robincamille** [comment]
Fixed it! Thanks for raising this issue. Cheers!
